name: "Build and Deploy Vercel"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vercel:
    name: "Build and Deploy Vercel"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Only set up preview environment for pull requests
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        if: github.event_name == 'pull_request'
        with:
          terraform_version: 1.1.0-beta1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Update terraform.tf to default to single workspace
      - name: Terraform Init, create TFC workspace
        if: github.event_name == 'pull_request'
        id: init-workspace
        run: |
          cd backend-terraform
          sed -i 's/tags = \["hashicupsBackend"\]/name = "hcup-be-'${GITHUB_REF}'"/g' terraform.tf
          terraform init -input=false

      - name: Build preview environment
        if: github.event_name == 'pull_request'
        id: build-preview-environment
        run: |
          cd backend-terraform
          terraform apply --auto-approve

      - name: Install and Build Preview Environment
        if: github.event_name == 'pull_request'
        run: |
          npm install
          REACT_APP_PUBLIC_API_URL=http://${terraform output -raw lb_dns_name} npm run build

      - name: Deploy Preview Environment
        uses: amondnet/vercel-action@v20.0.0
        id: vercel-action-preview
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Install and Build Prod Environment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          npm install
          npm run build

      - name: Deploy Prod Environment
        uses: amondnet/vercel-action@v20.0.0
        id: vercel-action-production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod "
